# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: tdolist
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Website of tdolist
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tdolist.github.io" # the base hostname & protocol for your site
github_username:  tdolist

# Build settings
markdown: kramdown
kramdown:
  input: GFM

sass:
  style: :compressed

defaults:
  -
    scope:
      path: ""
      type: "legal"
    values:
      layout: "page"

collections:
  projects:
    output: true
  legal:
    output: true
